# Generated by Django 6.0.6 on 2026-06-13 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6')], max_length=5)),
                ('academic_year', models.CharField(max_length=9)),
                ('credit_limit', models.PositiveIntegerField(default=30)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='catalog.specialization')),
            ],
            options={
                'ordering': ['specialization', 'name'],
                'unique_together': {('specialization', 'name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.PositiveIntegerField()),
                ('coefficient', models.FloatField(default=1.0)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('responsible_tutor', models.ForeignKey(blank=True, limit_choices_to={'role': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
    ]
