# Generated by Django 6.0.6 on 2026-06-13 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dropped', 'Dropped')], default='pending', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catalog.subject')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_assessment', models.FloatField(blank=True, null=True)),
                ('final_exam', models.FloatField(blank=True, null=True)),
                ('calculated_grade', models.FloatField(blank=True, null=True)),
                ('session', models.CharField(choices=[('main', 'Main Session'), ('retake', 'Retake Session')], default='main', max_length=10)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='enrollment.enrollment')),
            ],
        ),
    ]
